### PR TITLE
feat: playground cli api

### PR DESCRIPTION
**Pull request by Dev79844**
### Changes:
- Implemented functions for initializing db and closing conn with db
- Added functions for get, set, delete
- Added function for parsing http request
- Added a global function to execute commands

### CODE REVIEW

**Comment by lucifercr07** [comment]
@Dev79844 can you please close and reopen the PR, this would allow the workflows to trigger and validate.

**Comment by karandixit10** [comment]
@Dev79844 Are you done with your changes shall I add unit test and integration tests for the same?
I can working on #731 issue

**Comment by Dev79844** [comment]
Yes. Please go ahead

**Comment by lucifercr07** [comment]
@Dev79844 can you please resolve the conflicts.

**Comment by Dev79844** [comment]
@lucifercr07 resolved the conflicts

**Pull request merged**
